/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.rretzbach.bobchat.core;

import de.rretzbach.bobchat.irc.Channel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.ListView;
import org.openide.nodes.AbstractNode;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//de.rretzbach.bobchat.core//NickList//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "NickListTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "rightSlidingSide", openAtStartup = false)
//@ActionID(category = "Window", id = "de.rretzbach.bobchat.core.NickListTopComponent")
//@ActionReference(path = "Menu/Window" /*, position = 333 */)
//@TopComponent.OpenActionRegistration(
//    displayName = "#CTL_NickListAction",
//preferredID = "NickListTopComponent")
//@Messages({
//    "CTL_NickListAction=NickList",
//    "CTL_NickListTopComponent=NickList Window",
//    "HINT_NickListTopComponent=This is a NickList window"
//})
public final class NickListTopComponent extends TopComponent implements ExplorerManager.Provider {
    private transient ExplorerManager em = new ExplorerManager();
    private Channel channel;

    public NickListTopComponent() {
        initComponents();
        setName("???");
        //setToolTipText(Bundle.HINT_NickListTopComponent());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new ListView();

        setLayout(new java.awt.BorderLayout());
        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    public void registerComponent() {
        // TODO
        final AbstractNode rootNode = new AbstractNode(new NickListNodes(this.channel));
        em.setRootContext(rootNode);
        em.getRootContext().setDisplayName("Users");
    }

    public void setChannel(Channel channel) {
        this.channel = channel;
        setName(channel.getLabel() + " users");
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return this.em;
    }
}
